import jsPDF from 'jspdf';
import { formatCurrencyToMillions } from './format-utils';

interface ReportData {
    period: {
        year: number;
        month?: number;
        monthName?: string;
    };
    sales: {
        totalSales: number;
        grossAmount: number;
        netAmount: number;
        vatAmount: number;
        salesCount: number;
        avgSaleValue: number;
    };
    treasury: {
        totalPaid: number;
        challanCount: number;
        avgChallanAmount: number;
        challans: Array<{
            tokenNo: string;
            amount: number;
            date: string;
            bank: string;
        }>;
    };
    vat: {
        payable: number;
        paid: number;
        outstanding: number;
        rate: number;
    };
    closingBalance: {
        available: number;
        used: number;
        currentMonthAddition: number;
    };
    imports: {
        totalVat: number;
        totalAt: number;
        importCount: number;
    };
    summary: {
        compliance: number;
        status: string;
    };
}

export function generateComprehensiveReportPDF(reportData: ReportData[], options: { type: string; year: number; month?: number }) {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        putOnlyUsedFonts: true,
        compress: true
    });

    // Add UTF-8 support
    doc.setProperties({
        title: 'VAT Report',
        subject: 'Comprehensive VAT Report',
        author: 'M S RAHMAN TRADERS',
        creator: 'VAT Management System'
    });

    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    let yPosition = 20;

    // Colors
    const colors = {
        primary: [41, 128, 185],
        secondary: [52, 73, 94],
        success: [39, 174, 96],
        warning: [243, 156, 18],
        danger: [231, 76, 60],
        light: [248, 249, 250],
        lightBlue: [235, 245, 255],
        lightGreen: [235, 255, 235],
        lightRed: [255, 235, 235],
        border: [220, 220, 220]
    };

    // Helper functions
    const checkPageBreak = (requiredSpace: number) => {
        if (yPosition + requiredSpace > pageHeight - 30) {
            addFooter();
            doc.addPage();
            yPosition = 20;
            addHeader();
        }
    };

    const drawRect = (x: number, y: number, width: number, height: number, fillColor?: number[], borderColor?: number[]) => {
        if (fillColor) {
            doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
            doc.rect(x, y, width, height, 'F');
        }
        if (borderColor) {
            doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
            doc.setLineWidth(0.5);
            doc.rect(x, y, width, height, 'S');
        }
    };

    const addHeader = () => {
        // Header background
        drawRect(0, 0, pageWidth, 45, colors.primary);

        // Company logo placeholder
        doc.setFillColor(255, 255, 255);
        doc.circle(25, 22, 8, 'F');
        doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('MSR', 25, 25, { align: 'center' });

        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text('COMPREHENSIVE VAT REPORT', pageWidth / 2, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text('M S RAHMAN TRADERS', pageWidth / 2, 30, { align: 'center' });

        doc.setFontSize(9);
        doc.text('Tax Compliance & Business Intelligence Report', pageWidth / 2, 38, { align: 'center' });

        yPosition = 55;
    };

    const addFooter = () => {
        const footerY = pageHeight - 20;

        // Footer line
        doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
        doc.setLineWidth(0.5);
        doc.line(20, footerY - 5, pageWidth - 20, footerY - 5);

        doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text('Generated by VAT Management System', 20, footerY);
        doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageWidth / 2, footerY, { align: 'center' });
        doc.text(new Date().toLocaleDateString(), pageWidth - 20, footerY, { align: 'right' });
    };

    const addSectionHeader = (title: string, icon: string = '■') => {
        checkPageBreak(20);

        // Section background
        drawRect(15, yPosition - 2, pageWidth - 30, 14, colors.lightBlue, colors.border);

        doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`${icon} ${title}`, 20, yPosition + 8);
        yPosition += 20;
    };

    const addInfoBox = (title: string, items: Array<{ label: string, value: string, highlight?: boolean }>, bgColor: number[] = colors.light) => {
        const boxHeight = items.length * 7 + 15;
        checkPageBreak(boxHeight + 5);

        // Box background
        drawRect(20, yPosition - 3, pageWidth - 40, boxHeight, bgColor, colors.border);

        // Box title
        doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(title, 25, yPosition + 8);
        yPosition += 15;

        // Box items
        items.forEach(item => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
            doc.text(item.label, 30, yPosition);

            if (item.highlight) {
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
            } else {
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(0, 0, 0);
            }
            doc.text(item.value, pageWidth - 50, yPosition, { align: 'right' });
            yPosition += 7;
        });

        yPosition += 8;
    };

    const addSummaryCards = (data: ReportData) => {
        checkPageBreak(50);

        const cardWidth = (pageWidth - 50) / 4;
        const cardHeight = 35;
        const startX = 20;

        // Card 1: Total Sales
        drawRect(startX, yPosition, cardWidth - 2, cardHeight, colors.lightGreen, colors.success);
        doc.setTextColor(colors.success[0], colors.success[1], colors.success[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('TOTAL SALES', startX + 5, yPosition + 8);
        doc.setFontSize(12);
        doc.text(formatCurrencyToMillions(data.sales.grossAmount), startX + 5, yPosition + 18);
        doc.setFontSize(7);
        doc.text(`${data.sales.salesCount} transactions`, startX + 5, yPosition + 28);

        // Card 2: VAT Payable
        const card2X = startX + cardWidth;
        drawRect(card2X, yPosition, cardWidth - 2, cardHeight, colors.lightBlue, colors.primary);
        doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('VAT PAYABLE', card2X + 5, yPosition + 8);
        doc.setFontSize(12);
        doc.text(formatCurrencyToMillions(data.vat.payable), card2X + 5, yPosition + 18);
        doc.setFontSize(7);
        doc.text(`${(data.vat.rate * 100).toFixed(1)}% rate`, card2X + 5, yPosition + 28);

        // Card 3: Treasury Paid
        const card3X = startX + cardWidth * 2;
        drawRect(card3X, yPosition, cardWidth - 2, cardHeight, [255, 248, 220], colors.warning);
        doc.setTextColor(colors.warning[0], colors.warning[1], colors.warning[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('TREASURY PAID', card3X + 5, yPosition + 8);
        doc.setFontSize(12);
        doc.text(formatCurrencyToMillions(data.treasury.totalPaid), card3X + 5, yPosition + 18);
        doc.setFontSize(7);
        doc.text(`${data.treasury.challanCount} challans`, card3X + 5, yPosition + 28);

        // Card 4: Outstanding
        const card4X = startX + cardWidth * 3;
        const outstandingColor = data.vat.outstanding > 0 ? colors.danger : colors.success;
        const outstandingBg = data.vat.outstanding > 0 ? colors.lightRed : colors.lightGreen;
        drawRect(card4X, yPosition, cardWidth - 2, cardHeight, outstandingBg, outstandingColor);
        doc.setTextColor(outstandingColor[0], outstandingColor[1], outstandingColor[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('OUTSTANDING', card4X + 5, yPosition + 8);
        doc.setFontSize(12);
        doc.text(formatCurrencyToMillions(data.vat.outstanding), card4X + 5, yPosition + 18);
        doc.setFontSize(7);
        doc.text(data.summary.status.toUpperCase(), card4X + 5, yPosition + 28);

        yPosition += cardHeight + 15;
    };

    const addTable = (headers: string[], rows: string[][], title?: string) => {
        if (title) {
            checkPageBreak(20);
            doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text(title, 20, yPosition);
            yPosition += 10;
        }

        const tableWidth = pageWidth - 40;
        const colWidth = tableWidth / headers.length;
        const rowHeight = 8;

        checkPageBreak((rows.length + 1) * rowHeight + 10);

        // Table headers
        drawRect(20, yPosition - 2, tableWidth, rowHeight, colors.secondary);
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');

        headers.forEach((header, i) => {
            doc.text(header, 25 + (i * colWidth), yPosition + 4);
        });
        yPosition += rowHeight;

        // Table rows
        rows.forEach((row, rowIndex) => {
            const bgColor = rowIndex % 2 === 0 ? [255, 255, 255] : colors.light;
            drawRect(20, yPosition - 2, tableWidth, rowHeight, bgColor, colors.border);

            doc.setTextColor(0, 0, 0);
            doc.setFontSize(7);
            doc.setFont('helvetica', 'normal');

            row.forEach((cell, i) => {
                const x = 25 + (i * colWidth);
                const maxWidth = colWidth - 10;

                if (cell.length > 20) {
                    doc.text(cell.substring(0, 17) + '...', x, yPosition + 4);
                } else {
                    doc.text(cell, x, yPosition + 4);
                }
            });
            yPosition += rowHeight;
        });

        yPosition += 10;
    };

    // Start generating PDF
    addHeader();

    // Report metadata
    addSectionHeader('REPORT INFORMATION', '■');
    addInfoBox('Report Details', [
        { label: 'Report Type:', value: options.type.toUpperCase(), highlight: true },
        { label: 'Period:', value: options.month ? getMonthName(options.month) + ' ' + options.year : 'Year ' + options.year, highlight: true },
        { label: 'Generated:', value: new Date().toLocaleString() },
        { label: 'Total Periods:', value: reportData.length.toString() }
    ]);

    // Process each period
    reportData.forEach((data, index) => {
        if (reportData.length > 1) {
            addSectionHeader(`PERIOD: ${data.period.monthName || `Year ${data.period.year}`}`, '■');
        }

        // Summary cards
        addSummaryCards(data);

        // Sales breakdown
        addSectionHeader('SALES ANALYSIS', '■');
        addInfoBox('Sales Performance', [
            { label: 'Gross Sales:', value: formatCurrencyToMillions(data.sales.grossAmount), highlight: true },
            { label: 'Net Sales (Ex-VAT):', value: formatCurrencyToMillions(data.sales.netAmount) },
            { label: 'VAT Amount:', value: formatCurrencyToMillions(data.sales.vatAmount) },
            { label: 'Total Transactions:', value: data.sales.salesCount.toString() },
            { label: 'Average Sale Value:', value: formatCurrencyToMillions(data.sales.avgSaleValue) }
        ], colors.lightGreen);

        // VAT compliance
        addSectionHeader('VAT COMPLIANCE', '■');
        addInfoBox('VAT Analysis', [
            { label: 'VAT Payable:', value: formatCurrencyToMillions(data.vat.payable), highlight: true },
            { label: 'Treasury Payments:', value: formatCurrencyToMillions(data.vat.paid) },
            { label: 'Outstanding Balance:', value: formatCurrencyToMillions(data.vat.outstanding), highlight: data.vat.outstanding > 0 },
            { label: 'Compliance Rate:', value: `${data.summary.compliance.toFixed(1)}%`, highlight: true },
            { label: 'Status:', value: data.summary.status.toUpperCase(), highlight: true }
        ], colors.lightBlue);

        // Closing balance
        addSectionHeader('CLOSING BALANCE', '■');
        addInfoBox('Import AT & VAT Adjustments', [
            { label: 'Available Balance:', value: formatCurrencyToMillions(data.closingBalance.available) },
            { label: 'Used This Period:', value: formatCurrencyToMillions(data.closingBalance.used) },
            { label: 'Current Addition:', value: formatCurrencyToMillions(data.closingBalance.currentMonthAddition) },
            { label: 'Net Available:', value: formatCurrencyToMillions(data.closingBalance.available - data.closingBalance.used), highlight: true }
        ]);

        // Import payments
        addSectionHeader('IMPORT STAGE PAYMENTS', '■');
        addInfoBox('Import Duties & Taxes', [
            { label: 'Import VAT Paid:', value: formatCurrencyToMillions(data.imports.totalVat) },
            { label: 'Advance Tax (AT):', value: formatCurrencyToMillions(data.imports.totalAt) },
            { label: 'Import Entries:', value: `${data.imports.importCount} BOE` },
            { label: 'Total Import Payments:', value: formatCurrencyToMillions(data.imports.totalVat + data.imports.totalAt), highlight: true }
        ]);

        // Treasury challans table
        if (data.treasury.challans.length > 0) {
            addSectionHeader('TREASURY CHALLANS', '■');
            const challanRows = data.treasury.challans.map(challan => [
                challan.tokenNo,
                formatCurrencyToMillions(challan.amount),
                new Date(challan.date).toLocaleDateString(),
                challan.bank
            ]);

            addTable(
                ['Token No', 'Amount', 'Date', 'Bank'],
                challanRows,
                `Treasury Payments (${data.treasury.challanCount} challans)`
            );
        }

        if (index < reportData.length - 1) {
            doc.addPage();
            yPosition = 20;
            addHeader();
        }
    });

    // Final summary if multiple periods
    if (reportData.length > 1) {
        addSectionHeader('OVERALL SUMMARY', '■');
        const totalSales = reportData.reduce((sum, d) => sum + d.sales.grossAmount, 0);
        const totalVatPayable = reportData.reduce((sum, d) => sum + d.vat.payable, 0);
        const totalTreasuryPaid = reportData.reduce((sum, d) => sum + d.treasury.totalPaid, 0);
        const totalOutstanding = reportData.reduce((sum, d) => sum + d.vat.outstanding, 0);

        addInfoBox('Consolidated Figures', [
            { label: 'Total Sales (All Periods):', value: formatCurrencyToMillions(totalSales), highlight: true },
            { label: 'Total VAT Payable:', value: formatCurrencyToMillions(totalVatPayable), highlight: true },
            { label: 'Total Treasury Paid:', value: formatCurrencyToMillions(totalTreasuryPaid) },
            { label: 'Total Outstanding:', value: formatCurrencyToMillions(totalOutstanding), highlight: totalOutstanding > 0 },
            { label: 'Overall Compliance:', value: `${totalVatPayable > 0 ? ((totalTreasuryPaid / totalVatPayable) * 100).toFixed(1) : '100.0'}%`, highlight: true }
        ], colors.lightBlue);
    }

    addFooter();
    return doc;
}

function getMonthName(month: number): string {
    const monthNames = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return monthNames[month - 1] || 'Unknown';
}